/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_callisto_processstats_SysConf */

#ifndef _Included_net_callisto_processstats_SysConf
#define _Included_net_callisto_processstats_SysConf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_callisto_processstats_SysConf
 * Method:    getCLK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_callisto_processstats_SysConf_getCLK
  (JNIEnv *, jclass);

/*
 * Class:     net_callisto_processstats_SysConf
 * Method:    getPageSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_callisto_processstats_SysConf_getPageSize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
